# leave a url to make hugo serve displayed a good url
baseURL = "https://think.fr"
languageCode = "fr-FR"
title = "Think - Titre de ma formation"
description = "Description de ma formation"
disableKinds = ["sitemap", "RSS"]
# Theme think should be first to get partials working
theme = ["think", "reveal-hugo"]
themesDir = "./themes"

# Specific settings for static content
# Do not change if you want real static content
relativeURLs = true
uglyURLs = true

[author]
# These properties are used some slides
name = "Prénom Nom"
mail = "prenom.nom@think.fr"


[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
# this theme shouldn't be changed use custom_css instead
custom_theme = "think/css/think-new.css"
# add the specified in static folder
# ex: static/css/custom.css
#custom_css = "css/custom.css"

# Presentation size - do not change if possible
margin = 0.05
width = 1600
height = 900

# These RevealJS's settings could be change
# Here are some defaults
# More configuration options here
# https://github.com/hakimel/reveal.js/#configuration

highlight_theme = "solarized-dark"
transition = "slide"
transition_speed = "fast"
mouse_wheel = true
controls = false
#slide_number = true
progressBar = false
