baseURL = "https://think.fr"
languageCode = "fr-FR"
title = "Think - Nom de la formation"
description = "Description de la formation"
disableKinds = ["sitemap", "RSS"]
theme = ["reveal-hugo", "think"]
themesDir = "./themes"

# Specific settings for static content
relativeURLs = true
uglyURLs = true

[author]
name = "Formateur Think"
mail = "Email Formateur en @think.fr"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

# More configuration options here
# https://github.com/hakimel/reveal.js/#configuration
# https://github.com/hakimel/reveal.js/#presentation-size 
[params.reveal_hugo]
custom_theme = "think/css/think.css"
# add the specified in static folder
# ex: static/css/custom.css
#custom_css = "css/custom.css"
margin = 0.2
# highlightjs theme
# available themes in themes/reveal-hugo/static/highlight-js
highlight_theme = "solarized-dark"
transition = "slide"
transition_speed = "fast"
#mouse_wheel = true