variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: registry.gitlab.com/pages/hugo:latest

stages:
  - check
  - build
  - deploy
.build_template: &build_template
  script:
    - hugo 

test:
  stage: check
  <<: *build_template
  except:
  - master

generate:
  stage: build
  <<: *build_template
  artifacts:
    paths:
    - public
  only:
  - master

send_gcp:
  stage: deploy
  image: google/cloud-sdk:alpine
  script:
    - echo $BUCKET_SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gsutil cp -r public gs://$BUCKET_NAME/${CI_PROJECT_NAMESPACE/thinkfr\//}/$CI_PROJECT_NAME

