variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: registry.gitlab.com/pages/hugo:latest

stages:
  - check
  - deploy
.build_template: &build_template
  script:
    - hugo 

test:
  stage: check
  <<: *build_template

generate:
  stage: deploy
  <<: *build_template
  artifacts:
    paths:
    - public
  only:
  - master
